# Generated by Django 5.0 on 2026-03-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('soil_ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('elevation', models.FloatField()),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
