# Generated by Django 5.0 on 2026-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_suitability_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('ai_explanation', models.JSONField()),
            ],
            options={
                'verbose_name': 'Coffee Suitability Log',
                'verbose_name_plural': 'Coffee Suitability Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
